[tools]
awscli = { version = "latest", symlink_bins = "true" }
"ubi:ddev/ddev" = "latest"
helm = "latest"
k3d = "latest"
k9s = "latest"
kubectl = "latest"
terraform = "latest"
uv = "latest"
"ubi:tsenart/vegeta" = "latest"
mkcert = "latest"
trivy = "latest"
