# Drupal CMS with FrankenPHP (via ddev-frankenphp add-on)
# Run: ddev add-on get ddev/ddev-frankenphp

name: drupal-cms-perftest
type: drupal11
docroot: web
php_version: "8.4"
database:
  type: mariadb
  version: "10.11"
