apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tutorials-and-workshops
resources:
  - deployment.yaml
configMapGenerator:
- name: rclone-config
  files:
  - rclone.conf
labels:
  - pairs:
      app: rclone-lab
    includeSelectors: true